TEAM-DDIS/be14-fin-DDIS-FE

- src/components/attendance/AttendanceSummaryCard.vue
- src/components/attendance/PersonalEventCard.vue
- src/components/attendance/WeeklyOvertimeCard.vue
- src/components/calendar/HomePersonalCalendar.vue
- src/components/calendar/HomeTeamCalendar.vue
- src/components/calendar/PersonalCalendar.vue
- src/components/calendar/TeamCalendar.vue
- src/main.js
- src/pages/MyAttendancePage.vue
1. 개인 일정 등록 구현
2. 캘린더 라벨 설명 추가
- #33 
- #32 
https://github.com/user-attachments/assets/5afdd432-ae54-4325-bda1-dc2ee32a2a1e
> [FEAT] 개인 일정 등록 구현

- src/components/draftdoc/draftcreate/DraftTemplateList.vue
- src/components/sidebar/SubSidebar.vue
- src/router/index.js
1. 전자결재 기안 작성 시 양식 선택함 리팩토링(공동 사용 라이브러리 적용)
2. 리팩토링 화면 캡쳐 첨부
3. 3
- #35 
> [REFACTOR] 기안 작성시 양식 선택 화면 리팩토링

- public/attendance.json
- src/components/attendance/MeetingEventCard.vue
- src/components/attendance/TeamWorkStatus.vue
- src/components/attendance/TeamWorkStatusCard.vue
- src/components/attendance/TodayMeetingCard.vue
- src/components/calendar/PersonalCalendar.vue
- src/components/calendar/TeamCalendar.vue
- src/components/sidebar/SubSidebar.vue
- src/pages/MyAttendancePage.vue
- src/pages/TeamAttendancePage.vue
- src/router/index.js
1. 팀 근태 현황 페이지 구현
2. 팀 근무 상태 현황
3. 오늘 팀 회의 일정
4. 팀 캘린더
- #26 
- #20 
- #22 
- #33 
https://github.com/user-attachments/assets/c93de7aa-659f-47b4-aafa-575fb4f4ac6e
> [FEAT] 팀 근태 현황 페이지 구현

- src/router/index.js
> [STYLE] 라우터 주석 해제

- public/org.json
- src/App.vue
- src/assets/main.css
- src/components/org/appointment/Appointment.vue
- src/components/org/appointment/AppointmentDetail.vue
- src/components/org/appointment/RegisterAppointment.vue
- src/components/org/introduction/EditDeptModal.vue
- src/components/org/introduction/EditJobModal.vue
- src/components/org/introduction/Introduction.vue
- src/components/org/introduction/JobDetail.vue
- src/components/org/structure/EditHierarchy.vue
- src/components/org/structure/EditStructure.vue
- src/components/org/structure/Hierarchy.vue
- src/components/org/structure/HierarchyAll.vue
- src/components/org/structure/Structure.vue
- src/components/sidebar/SubSidebar.vue
- src/main.js
- src/router/index.js
1. 조직도에서 조직 이동하는 기능 구현 중 (미완)
2.  사이드바 라우터 수정
- 2차 탭 커서 방지
- index.js에 라우터 설정 및 SubSidebar에 3차 탭 등록
> [FEAT] 조직 구조 편집 기능 구현 및 사이드바 수정

- src/components/post/PostDetailPage.vue
- src/components/post/PostEnroll.vue
- src/components/post/PostListPage.vue
- src/router/index.js
1. 공지사항 상세 조회 페이지 구현 
- close #58 
https://github.com/user-attachments/assets/2a1ae07c-8935-4501-b10d-f9254dc7afcd
> [FEAT] 공지사항 상세 조회 페이지 구현

- public/attendance.json
- src/components/correction/AllCorrectionRegistCard.vue
- src/components/correction/AllCorrectionUsedCard.vue
- src/components/correction/CorrectionApproveEvent.vue
- src/components/correction/CorrectionRegistEvent.vue
- src/components/correction/CorrectionRejectEvent.vue
- src/components/correction/MyCorrectionRegistCard.vue
- src/components/correction/MyCorrectionUsedCard.vue
- src/pages/AllCorrectionPage.vue
- src/pages/MyCorrectionPage.vue
- src/router/index.js
1. 내 출근 정정 관리 페이지 구현
2. 전체 출근 정정 관리 페이지 구현
- #76 
https://github.com/user-attachments/assets/56e90141-0d02-4d68-a7dc-d635ee3de85f
> [FEAT] 출근 정정 관리 페이지 구현

- src/components/draftdoc/MyDraft.vue
1. 전자결재 기안함 화면 구현
2. 화면 녹화본 첨부
- #80 
https://github.com/user-attachments/assets/967dfdde-a1d5-40dd-ace4-42c8d5177aa9
> [FEAT] 전자결재 기안함 화면 구현

- src/components/org/structure/AddModal.vue
- src/components/org/structure/DeleteModal.vue
- src/components/org/structure/Hierarchy.vue
- src/pages/org/AppointmentDetailPage.vue
- src/pages/org/AppointmentPage.vue
- src/pages/org/EditStructurePage.vue
- src/pages/org/RegisterAppointmentPage.vue
- src/pages/org/StructurePage.vue
- src/router/index.js
> [FEAT] 조직 등록 및 삭제 모달 백엔드 연동

- src/components/attendance/AttendanceSummaryCard.vue
1. 출퇴근 백엔드 연동
2. 점심시간 (12:00 ~ 13:00)에는 근무 시간 측정 X
점심시간에는 타이머 멈춤
> [REFACTOR] 출퇴근 백엔드 연동

- src/components/Evaluation/MyEvalsPage.vue
- src/components/sidebar/SubSidebar.vue
- src/pages/achievment/AchievmentPage.vue
- src/router/index.js
1. 성과 이력 페이지 제작
2. 내가 평가한 평가 페이지 제작
3. 
> [FEAT] 성과 이력 페이지 제작, 내가 평가한 평가 페이지 제작

- src/components/attendance/AttendanceSummaryCard.vue
- src/components/calendar/PersonalCalendar.vue
- src/components/calendar/TeamCalendar.vue
- src/components/sidebar/AttendanceCard.vue
1. 근무 시간 타이머 (점심시간은 측정 X)
2. 개인 일정 등록
3. 회의 일정 등록
4. 사이드 출퇴근 카드 백엔드 연동
[근무, 일정 연동]
https://github.com/user-attachments/assets/c81d7602-af1b-4c14-9767-a808a6a813d0
[사이드 출퇴근 카드 연동]
https://github.com/user-attachments/assets/102e8db0-1f23-477d-887c-012d60f57969
> [REFACTOR] 개인/팀 근태 현황 + 사이드 출퇴근 카드 백엔드 연동

- package.json
- src/components/home/FavoriteMenu.vue
- src/components/home/MenuModal.vue
- src/components/home/MenuSidebar.vue
- src/components/home/MenuSubSidebar.vue
- src/pages/MainPage.vue
1. 기본 홈 구성
2. 자주 쓰는 메뉴 > 메뉴 편집 버튼 클릭 시 모달
3. 모달 내 필요 API 호출
4. 드래그 앤 드롭 추가
- #111 
https://github.com/user-attachments/assets/2096a26e-c4bd-43c0-952f-ab4f12bce5bc
> 백엔드 연동 동시 진행입니다.
> 드래그앤드롭 패키지 추가되었습니다. npm install 한번씩..!
> [FEAT] 자주 쓰는 메뉴 모달 구현

- package.json
- src/components/home/FavoriteMenu.vue
- src/components/home/MenuModal.vue
- src/components/home/MenuSidebar.vue
- src/components/home/MenuSubSidebar.vue
- src/components/salary/PayrollModal.vue
- src/components/salary/RetirementModal.vue
- src/pages/MainPage.vue
- src/pages/salary/PayrollSlipIssue.vue
- src/pages/salary/RetirementPaymentStatus.vue
1. 급여, 퇴직 백엔드 요청 시 header에  token 값 추가
> 기존 PR merge가 안 되어서 중복된 commit 내용이 업로드 되었습니다.. 참고부탁드립니다..!
> [REFACTOR] header token 추가

- src/components/attendance/WeeklyOvertimeCard.vue
- src/pages/attendance/MyAttendancePage.vue
> [REFACTOR] 주간 초과 근무 현황 백엔드 연동

- src/assets/main.css
- src/pages/org/RegisterAppointmentPage.vue
1. 인사발령 등록 데이터 추가됨 ㅎㅎ
- 이 데이터로 batch 확인 예정 (12일 자정)
> [FEAT] 인사발령 등록 백엔드 연동

- src/components/eapproval/ApprovalLineModal.vue
- src/pages/eapproval/DraftFormA.vue
1. 자동 매칭된 결재라인 내 기안자 정보 추가 
2. 결재선 지정 모달 구현 (하이라키 미적용) 
- #126 
-
- 자동매칭 결재선 내 기안자 추가
- 결재선 지정 모달 (조직도 하이라키 미적용)
> [REFACTOR]결재라인 기안자 추가 및 결재선 지정 모달 구현

- src/components/commute/AllCommuteCard.vue
- src/components/commute/EmployeeInfo.vue
- src/components/commute/MyCommuteCard.vue
- src/components/commute/MyCommuteSummary.vue
- src/components/commute/OtherCommuteCard.vue
- src/components/commute/OtherCommuteSummary.vue
- src/pages/attendance/AllCommutePage.vue
- src/pages/attendance/MyCommutePage.vue
- src/pages/attendance/OtherCommutePage.vue
1. 출퇴근 관리 백엔드 연동
https://github.com/user-attachments/assets/f4d0dd6b-1494-4e82-b957-4021dbe75003
> [REFACTOR] 출퇴근 관리 백엔드 연동

- src/components/post/PostListPage.vue
> [REFACTOR] 공지사항 목록 조회 백엔드 연동

- src/components/post/PostDetailPage.vue
- src/components/post/PostEnroll.vue
- src/components/post/PostListPage.vue
> [REFACTOR] 백엔드 연동

- package-lock.json
- package.json
- src/components/org/appointment/GetEmployeeModal.vue
- src/components/org/structure/EditHierarchy.vue
- src/components/org/structure/Hierarchy.vue
- src/components/org/structure/HierarchyAll.vue
- src/components/org/structure/HierarchyAppointment.vue
- src/pages/org/EditStructurePage.vue
- src/pages/org/RegisterAppointmentPage.vue
> [FEAT] 인사발령 등록 화면 수정

- src/components/employeeInfo/EmployeeEnroll.vue
- src/components/post/PostEnroll.vue
1. 사원 등록 백 프론트 연동
> 최종본 완성 시 추가 설명 작성하겠습니다.
> [REFACTOR] 사원 등록 수정

- src/components/employeeInfo/disciplinaryList.vue
> [FEAT] 징계 목록 조회 백엔드 연동

- src/components/attendance/OverTimeEventCard.vue
- src/components/attendance/WeeklyOvertimeCard.vue
- src/components/commute/AllCommuteCard.vue
1. 초과근무 신청 백엔드 연동
https://github.com/user-attachments/assets/4efdbbf5-9b1f-49ed-97a7-82ef2e739721
> [FEAT] 초과근무 신청 백엔드 연동

- src/components/salary/PayrollModal.vue
- src/pages/salary/PayrollSlip.vue
- src/pages/salary/PayrollSlipIssue.vue
- src/pages/salary/RetirementEstimate.vue
- src/pages/salary/RetirementPaymentStatus.vue
1. 급여 권한 설정
2. 403 페이지 연결
- #164 
> [REFACTOR] 급여 권한 설정

- src/components/employeeInfo/disciplinaryList.vue
1. 징계 목록 내 파일명을 클릭하면 다운로드 가능하게 구현
- close #170 
> [FEAT] 징계 목록 내 파일 다운로드 구현

- src/components/attendance/AttendanceSummaryCard.vue
- src/components/attendance/TeamWorkStatus.vue
- src/components/attendance/TeamWorkStatusCard.vue
- src/components/attendance/TodayMeetingCard.vue
- src/components/attendance/WeeklyOvertimeCard.vue
- src/components/calendar/PersonalCalendar.vue
- src/components/calendar/TeamCalendar.vue
- src/components/commute/EmployeeInfo.vue
- src/components/correction/AllCorrectionRegistCard.vue
- src/components/correction/AllCorrectionUsedCard.vue
- src/components/correction/MyCorrectionRegistCard.vue
- src/components/correction/MyCorrectionUsedCard.vue
- src/components/home/AttendanceBox.vue
- src/components/leave/AllLeaveRegistCard.vue
- src/components/leave/AllLeaveUsedCard.vue
- src/components/leave/LeaveCountCard.vue
- src/components/leave/MyLeaveRegistCard.vue
- src/components/leave/MyLeaveUsedCard.vue
- src/components/sidebar/AttendanceCard.vue
- src/pages/attendance/AllCommutePage.vue
- src/pages/attendance/AllCorrectionPage.vue
- src/pages/attendance/AllLeavePage.vue
- src/pages/attendance/MyCommutePage.vue
- src/pages/attendance/OtherCommutePage.vue
1. 권한 설정
https://github.com/user-attachments/assets/5e682cb9-99dc-41ec-96a5-58e087e66a54
> [REFACTOR] 권한 설정

- src/components/employeeInfo/MyEmployeePage.vue
1. 본인 정보 수정 기능 백엔드 연동
- close #182 
> [FEAT] 본인 정보 수정 기능 구현

- src/components/eapproval/ApprovalLineModal.vue
- src/components/eapproval/EHierarchy.vue
- src/pages/eapproval/DraftDetailPage.vue
- src/pages/eapproval/DraftFormA.vue
1. 결재라인 다중선택 기능 및 상세페이지 리팩토링
- #188 
> [REFACTOR] 결재라인 다중선택 기능 및 상세페이지 리팩토링

- src/components/employeeInfo/ContractEnroll.vue
- src/components/employeeInfo/ContractList.vue
- src/components/employeeInfo/EmployeeDetailPage.vue
- src/components/employeeInfo/EmployeeEnroll.vue
- src/components/employeeInfo/EmployeeList.vue
- src/components/employeeInfo/MyEmployeePage.vue
- src/components/employeeInfo/disciplinaryEnroll.vue
- src/components/employeeInfo/disciplinaryList.vue
- src/components/post/PostListPage.vue
1. 본인 정보 조회 내 인사발령 조회
2. 사원 정보 조회 내 인사발령 조회
3. 상세 버튼을 눌러 인사발령 상세 페이지로 이동
- close #190  close #191 
> [FEAT] 본인 정보 조회, 사원 정보 조회 내 인사발령 조회 및 상세 페이지 이동

- src/components/employeeInfo/ContractList.vue
- src/components/employeeInfo/EmployeeDetailPage.vue
- src/components/employeeInfo/EmployeeList.vue
- src/components/employeeInfo/disciplinaryList.vue
- src/components/post/PostDetailPage.vue
- src/components/post/PostListPage.vue
1. 인사팀과 일반사원의 권한을 분리합니다.
- close #194 
> [REFACTOR] 인사팀 권한 설정

- src/components/salary/PayrollModal.vue
- src/components/salary/RetirementModal.vue
- src/components/toast/BaseToast.vue
- src/pages/salary/PayrollSlip.vue
- src/pages/salary/PayrollSlipIssue.vue
- src/pages/salary/RetirementEstimate.vue
- src/pages/salary/RetirementPaymentStatus.vue
1. toast 컴포넌트 생성
2. 급여 toast 적용
3. 이메일 전송 중 추가 (UX)
- #197 
> 노션 > 개인페이지에 적용방법 정리해놨습니다!
> [STYLE] alert -> toast 일괄 적용

- src/components/attendance/AttendanceSummaryCard.vue
- src/components/attendance/TeamWorkStatus.vue
> [REFACTOR] 타이머 버그 수정

- src/pages/eapproval/DraftDetailPage.vue
- src/pages/eapproval/DraftFormA.vue
- src/pages/eapproval/ReceiverBoxPage.vue
- src/pages/eapproval/ReferenceBoxPage.vue
1. 기안문 상세조회 내 수신자, 참조자 렌더링 구현
- #206 
- 
>
> [FEAT] 기안문 상세조회 내 수신자, 참조자 렌더링 구현

- src/components/chatbot/ChatModal.vue
> [REFACTOR] 챗봇 API 수정

- src/components/employeeInfo/EmployeeDetailPage.vue
- src/components/employeeInfo/EmployeeEnroll.vue
- src/components/employeeInfo/EmployeeList.vue
- src/components/employeeInfo/MyEmployeePage.vue
- src/pages/eapproval/DraftTempListPage.vue
1. alert -> toast
-  close #212 
> [REFACTOR] alert -> toast

- src/components/chatbot/ChatModal.vue
- src/components/chatbot/FloatingChat.vue
- src/components/chatbot/MessageBubble.vue
- src/components/home/ReminderBox.vue
- src/pages/salary/PayrollSlip.vue
- src/pages/salary/PayrollSlipIssue.vue
1. 채팅 버튼 움직이게 했습니다
2. 채팅창 모달 움직이게 했습니다
3. 급여 , 추가했습니다
- #160 
> [REFACTOR] UI 리팩토링

- src/components/login/LoginPage.vue
> [FIX] bug fix
